# Generated by Django 2.0.5 on 2019-07-22 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(default='0.0.0.0')),
                ('cpu', models.FloatField(default=0)),
                ('mem', models.FloatField(default=0)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
