# Generated by Django 2.0.5 on 2019-07-02 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='addr',
            field=models.CharField(default='', max_length=120),
        ),
    ]
